import '@mobi/config/styles.css'

import type { Metadata } from 'next'

import { NavBar } from '@/feature/nav/ui'

export const metadata: Metadata = {
  title: 'Create Next App - Academy',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
